# Generated by Django 3.1.4 on 2021-04-19 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mensajes',
            new_name='mensaje',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='foto',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
