# Generated by Django 3.1.4 on 2021-04-21 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_auto_20210419_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['fecha']},
        ),
    ]
