# Generated by Django 3.1.4 on 2021-04-21 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_auto_20210421_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='id_Emisor',
            new_name='idEmisor',
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='id_Receptor',
            new_name='idReceptor',
        ),
    ]
